# name: Deploy React to S3 (OIDC)

# on:
#   push:
#     branches:
#       - main

# permissions:
#   id-token: write
#   contents: read

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

#       - name: Setup Node
#         uses: actions/setup-node@v4
#         with:
#           node-version: 18

#       # - name: Install Dependencies
#       #   run: npm install

#       # - name: Build
#       #   run: npm run build

#       - name: Configure AWS credentials (OIDC)
#         uses: aws-actions/configure-aws-credentials@v4
#         with:
#           role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
#           aws-region: ap-south-1

#       - name: Deploy to S3
#         run: |
#           aws s3 sync dist/ s3://react-app-prod-pardhiv --delete

#       # - name: Invalidate CloudFront
#       #   run: |
#       #     aws cloudfront create-invalidation \
#       #       --distribution-id YOUR_CF_DISTRIBUTION_ID \
#       #       --paths "/*"

name: Deploy Static Site to S3 (OIDC)

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-south-1

      - name: Upload files to S3
        run: |
          aws s3 sync . s3://react-app-prod-pardhiv --delete \
            --exclude ".git/*" \
            --exclude ".github/*"


      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E1CGRN7YBPOIL4\
            --paths "/*"
  